### ISSUE TITLE
Overflowing page and crooked cards

### ISSUE THREAD

**Issue by Lucekkk** [vizaav/vizaav.github.io#1]
![a84c53ae-624f-4e14-8c54-a81ccec385f4](https://github.com/user-attachments/assets/feea7074-ccd9-415d-93c9-8941daa3b63e)
![82bcb2c9-3013-4a17-a5ae-cd4b18fe5649](https://github.com/user-attachments/assets/a9b97209-8881-40db-9a92-aeb9c2e8d27a)
![1d9e480e-4e21-4674-b50a-ac2c64f5468b](https://github.com/user-attachments/assets/d2e15811-593f-482c-86a4-7604db837e6a)
![603d9934-ae84-4692-b9b3-c5c64a84fc55](https://github.com/user-attachments/assets/1083b597-1277-424d-aaf6-ff45919c18c0)

As you can see, there is a problem with overflowing document when you change the view on mobile. Try to set **overflow-x: hidden;** on html tag.
The second problem is crooked cards under the 'About me' and 'Projects' headers. It's noticeable when you try to scale the page.  Flexbox or Grid should solve the problem here.

**Comment by vizaav** [comment]
fixed in e3232f9ce199547334bc6c99d7158fa322a39ea7 thank you for your input!
